swagger: '2.0'
info:
  version: '1'
  title: Placement algorithm API
  description: REST API for executing/integrating 5GT placement algorithms
host: '127.0.0.1:8080'
basePath: /5gt/so/v1
schemes:
  - http
paths:
  /PAComp:
    get:
      summary: Retrieve a list of PA execution requests
      description: Retrieve the list of pending and completed PA requests.
      produces:
        - application/json
      responses:
        '200':
          description: List of PA requests
          schema:
            type: array
            items:
              $ref: '#/definitions/PAResponse'
    post:
      summary: Request the execution of a placement algorithm.
      description: >-
        Request the execution of a placement algorithm. The caller needs to
        implement a callback function and supply the relevant URI so that the PA
        can post there the result of its execution.-
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: PARequest
          in: body
          required: true
          description: Placement algorithm request information.
          schema:
            $ref: '#/definitions/PARequest'
      responses:
        '201':
          description: PA request created
        '200':
          description: PA request successfuly executed
          schema:
            $ref: '#/definitions/PAResponse'
  '/PAComp/{ReqId}':
    get:
      summary: Retrieve a specific PA request
      description: Retrieve status information about a specific PA request.
      produces:
        - application/json
      parameters:
        - name: ReqId
          in: path
          required: true
          description: Unique request identifier.
          type: string
      responses:
        '200':
          description: PA request information
          schema:
            $ref: '#/definitions/PARequest'
        '404':
          description: PA request not found
definitions:
  coordinate:
    description: Coordinate expressed in longitude and latitude
    type: object
    required:
      - longitude
      - latitude
    properties:
      longitude:
        description: coordinate longitude
        type: number
      latitude:
        description: coordinate latitude
        type: number
  location:
    description: Location expressed as a ball with a center coordinate and some radius
    type: object
    required:
      - coordinate
      - radius
    properties:
      center:
        $ref: '#/definitions/coordinate'
      radius:
        description: Location ball radius
        type: number
  NFVIPoP:
    required:
      - id
      - capabilities
    properties:
      id:
        description: NFVIPoP id
        type: string
      location:
        $ref: '#/definitions/location'
      gw_ip_address:
        description: Gateway IP address
        type: string
        format: ipv4
      capabilities:
        description: Capacity for different resources of the NFVIPoP
        type: object
        required:
          - cpu
          - ram
          - storage
        properties:
          cpu:
            description: NFVIPoP CPU capacity
            type: number
          ram:
            description: RAM capacity (in MB)
            type: number
          storage:
            description: storage capacity (in MB)
            type: number
          bandwidth:
            description: link capacity (in Mbps)
            type: number
      availableCapabilities:
        description: Available capacity for different resources of the NFVIPoP
        type: object
        required:
          - cpu
          - ram
          - storage
        properties:
          cpu:
            description: NFVIPoP CPU capacity
            type: number
          ram:
            description: RAM capacity (in MB)
            type: number
          storage:
            description: storage capacity (in MB)
            type: number
          bandwidth:
            description: link capacity (in Mbps)
            type: number
      failure_rate:
        description: Probability the NFVIPoP fails
        type: number
      internal_latency:
        description: Latency between two VNFs launched inside the NFVIPoP
        type: number
  LL:
    required:
      - LLid
      - capacity
      - delay
      - source
      - destination
    properties:
      LLid:
        description: Logical Link identifier
        type: string
      capacity:
        description: Logical Link capacity
        type: object
        properties:
          total:
            description: Total link capacity (Mbps)
            type: number
          available:
            description: Available link capacity (Mbps)
            type: number
      delay:
        description: Logical Link delay
        type: number
      source:
        description: Source NFVIPoP
        type: object
        required:
          - id
          - GwIpAddress
        properties:
          id:
            description: Source NFVIPoP id
            type: string
          GwIpAddress:
            description: Endpoint IP address
            type: string
            format: ipv4
      destination:
        description: Destination NFVIPoP
        type: object
        required:
          - id
          - GwIpAddress
        properties:
          id:
            description: Destination NFVIPoP id
            type: string
          GwIpAddress:
            description: Endpoint IP address
            type: string
            format: ipv4
  VNFCost:
    required:
      - cost
      - vnfid
      - NFVIPoPid
    properties:
      cost:
        description: Cost of placing the given VNF at the given NFVIPoP
        type: number
      vnfid:
        description: VNF identifier
        type: string
      NFVIPoPid:
        description: NFVIPoP identifier
        type: string
  LLCost:
    required:
      - cost
      - LL
    properties:
      cost:
        description: Cost of Mbps in the referenced LL
        type: number
      LL:
        description: NFVIPoPs LL identifier
        type: string
  VLCost:
    required:
      - cost
      - NFVIPoP
    properties:
      cost:
        description: Cost of Mbps to use a VL inside the specified NFVIPoP
        type: number
      NFVIPoP:
        description: NFVIPoPs identifier
        type: string
  NFVIInfo:
    required:
      - NFVIPoPs
      - LLs
    properties:
      resource_types:
        description: Allowed NFVI resource types
        type: array
        items:
          type: string
      NFVIPoPs:
        description: List of NFVIPoPs
        type: array
        items:
          $ref: '#/definitions/NFVIPoP'
      LLs:
        description: Logical links between NFVIPoPs
        type: array
        items:
          $ref: '#/definitions/LL'
      VNFCosts:
        description: Costs to place specific VNFs to specific NFVIPoPs
        type: array
        items:
          $ref: '#/definitions/VNFCost'
      LLCosts:
        description: Cost of using a LL between NFVIPoPs
        type: array
        items:
          $ref: '#/definitions/LLCost'
      VLCosts:
        description: Cost of using a VL inside a NFVIPoP
        type: array
        items:
          $ref: '#/definitions/VLCost'
  VNF:
    description: Information about a specific VNF.
    required:
      - VNFid
      - requirements
    properties:
      VNFid:
        description: VNF identifier
        type: string
      instances:
        description: Number of instances of this VNF to deploy
        type: number
      location:
        $ref: '#/definitions/location'
      requirements:
        description: VNF processing and other requirements
        type: object
        required:
          - cpu
          - ram
          - storage
        properties:
          cpu:
            description: CPU requirements
            type: number
          ram:
            description: Memory requirements (in MB)
            type: number
          storage:
            description: Storage requirements (in MB)
            type: number
      failure_rate:
        description: Probability that a VNF instance of this type fails.
        type: number
      processing_latency:
        description: >-
          Latency for a VNF instance with the specific characteristics to
          process a service request.
        type: number
  VNFLink:
    description: An edge between two VNFs in the VNFFG.
    required:
      - id
      - source
      - destination
    properties:
      id:
        description: Unique Virtual Link identifier
        type: string
      source:
        description: Source VNF id
        type: string
      destination:
        description: Destination VNF id
        type: string
      required_capacity:
        description: >-
          Maximum volume of traffic/s expected between these two VNFs and along
          this direction, and thus required capacity for the underlying VL
          between the NFVIPoPs that the two VNFs will be placed.
        type: number
      traversal_probability:
        description: >-
          Probability that a request traverses this link. This allows for
          branchesin the VNFFG (e.g., for load  balancing, etc.). If this
          parameter is omitted, it is assumed equal to 1.
        type: number
  NetworkService:
    description: Description of a network service.
    required:
      - VNFs
      - VNFLinks
      - name
      - id
    properties:
      id:
        description: Network service identifier
        type: string
      name:
        description: Name of the network service
        type: string
      VNFs:
        description: VNFs composing the service
        type: array
        items:
          $ref: '#/definitions/VNF'
      VNFLinks:
        description: Edges of the VNFFG
        type: array
        items:
          $ref: '#/definitions/VNFLink'
      max_latency:
        description: End-to-end latency constraint.
        type: number
      target_availability:
        description: Target service availability.
        type: number
      max_cost:
        description: Cost/budget constraint
        type: number
  PARequest:
    required:
      - ReqId
      - NFVI
      - NSD
      - callback
    type: object
    properties:
      ReqId:
        description: Unique request identifier
        type: string
      nfvi:
        $ref: '#/definitions/NFVIInfo'
      nsd:
        $ref: '#/definitions/NetworkService'
      callback:
        description: Callback URL
        type: string
        format: URL
  PAResponse:
    required:
      - worked
    description: Response to a PA request
    type: object
    properties:
      worked:
        description: Specifies if the PA worked and found a solution
        type: boolean
      result:
        description: Description of the PA result
        type: string
      usedNFVIPops:
        description: Array of all used NFVI PoPs with mapped VNFs
        type: array
        items:
          description: NFVIPoP with mapped VNFs
          type: object
          properties:
            NFVIPoPID:
              description: NFVI PoP ID
              type: string
            mappedVNFs:
              description: all VNFs mapped in this NFVI PoP
              type: array
              items:
                description: VNF ID
                type: string
      usedLLs:
        description: >-
          Array of all used LL between NFVIPoPs by the mapped Network Service
          VLs
        type: array
        items:
          description: LLs with mapped VLs
          type: object
          properties:
            LLID:
              description: LL ID
              type: string
            mappedVLs:
              description: all VLs mapped in this LL between NFVI PoP
              type: array
              items:
                description: VL ID
                type: string
      usedVLs:
        description: Array of all used VL inside NFVIPoPs by the mapped Network Service VLs
        type: array
        items:
          description: Intra NFVIPoP VLs with mapped VLs on top of them
          type: object
          properties:
            NFVIPoP:
              description: NFVIPoP ID
              type: string
            mappedVLs:
              description: all VLs mapped in this LL between NFVI PoP
              type: array
              items:
                description: VL ID
                type: string
      totalLatency:
        description: Network Sewrvice latency after placement
        type: number
      totalCost:
        description: cost of mapping the Network Service expressed in euros
        type: number
