# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PAResponseUsedLLs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, llid=None, mapped_v_ls=None):  # noqa: E501
        """PAResponseUsedLLs - a model defined in Swagger

        :param llid: The llid of this PAResponseUsedLLs.  # noqa: E501
        :type llid: str
        :param mapped_v_ls: The mapped_v_ls of this PAResponseUsedLLs.  # noqa: E501
        :type mapped_v_ls: List[str]
        """
        self.swagger_types = {
            'llid': str,
            'mapped_v_ls': List[str]
        }

        self.attribute_map = {
            'llid': 'LLID',
            'mapped_v_ls': 'mappedVLs'
        }

        self._llid = llid
        self._mapped_v_ls = mapped_v_ls

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PAResponse_usedLLs of this PAResponseUsedLLs.  # noqa: E501
        :rtype: PAResponseUsedLLs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def llid(self):
        """Gets the llid of this PAResponseUsedLLs.

        LL ID  # noqa: E501

        :return: The llid of this PAResponseUsedLLs.
        :rtype: str
        """
        return self._llid

    @llid.setter
    def llid(self, llid):
        """Sets the llid of this PAResponseUsedLLs.

        LL ID  # noqa: E501

        :param llid: The llid of this PAResponseUsedLLs.
        :type llid: str
        """

        self._llid = llid

    @property
    def mapped_v_ls(self):
        """Gets the mapped_v_ls of this PAResponseUsedLLs.

        all VLs mapped in this LL between NFVI PoP  # noqa: E501

        :return: The mapped_v_ls of this PAResponseUsedLLs.
        :rtype: List[str]
        """
        return self._mapped_v_ls

    @mapped_v_ls.setter
    def mapped_v_ls(self, mapped_v_ls):
        """Sets the mapped_v_ls of this PAResponseUsedLLs.

        all VLs mapped in this LL between NFVI PoP  # noqa: E501

        :param mapped_v_ls: The mapped_v_ls of this PAResponseUsedLLs.
        :type mapped_v_ls: List[str]
        """

        self._mapped_v_ls = mapped_v_ls
