# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VNFLink(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id=None, source=None, destination=None, required_capacity=None, traversal_probability=None):  # noqa: E501
        """VNFLink - a model defined in Swagger

        :param id: The id of this VNFLink.  # noqa: E501
        :type id: str
        :param source: The source of this VNFLink.  # noqa: E501
        :type source: str
        :param destination: The destination of this VNFLink.  # noqa: E501
        :type destination: str
        :param required_capacity: The required_capacity of this VNFLink.  # noqa: E501
        :type required_capacity: float
        :param traversal_probability: The traversal_probability of this VNFLink.  # noqa: E501
        :type traversal_probability: float
        """
        self.swagger_types = {
            'id': str,
            'source': str,
            'destination': str,
            'required_capacity': float,
            'traversal_probability': float
        }

        self.attribute_map = {
            'id': 'id',
            'source': 'source',
            'destination': 'destination',
            'required_capacity': 'required_capacity',
            'traversal_probability': 'traversal_probability'
        }

        self._id = id
        self._source = source
        self._destination = destination
        self._required_capacity = required_capacity
        self._traversal_probability = traversal_probability

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VNFLink of this VNFLink.  # noqa: E501
        :rtype: VNFLink
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this VNFLink.

        Unique Virtual Link identifier  # noqa: E501

        :return: The id of this VNFLink.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VNFLink.

        Unique Virtual Link identifier  # noqa: E501

        :param id: The id of this VNFLink.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def source(self):
        """Gets the source of this VNFLink.

        Source VNF id  # noqa: E501

        :return: The source of this VNFLink.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this VNFLink.

        Source VNF id  # noqa: E501

        :param source: The source of this VNFLink.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def destination(self):
        """Gets the destination of this VNFLink.

        Destination VNF id  # noqa: E501

        :return: The destination of this VNFLink.
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this VNFLink.

        Destination VNF id  # noqa: E501

        :param destination: The destination of this VNFLink.
        :type destination: str
        """
        if destination is None:
            raise ValueError("Invalid value for `destination`, must not be `None`")  # noqa: E501

        self._destination = destination

    @property
    def required_capacity(self):
        """Gets the required_capacity of this VNFLink.

        Maximum volume of traffic/s expected between these two VNFs and along this direction, and thus required capacity for the underlying VL between the NFVIPoPs that the two VNFs will be placed.  # noqa: E501

        :return: The required_capacity of this VNFLink.
        :rtype: float
        """
        return self._required_capacity

    @required_capacity.setter
    def required_capacity(self, required_capacity):
        """Sets the required_capacity of this VNFLink.

        Maximum volume of traffic/s expected between these two VNFs and along this direction, and thus required capacity for the underlying VL between the NFVIPoPs that the two VNFs will be placed.  # noqa: E501

        :param required_capacity: The required_capacity of this VNFLink.
        :type required_capacity: float
        """

        self._required_capacity = required_capacity

    @property
    def traversal_probability(self):
        """Gets the traversal_probability of this VNFLink.

        Probability that a request traverses this link. This allows for branchesin the VNFFG (e.g., for load  balancing, etc.). If this parameter is omitted, it is assumed equal to 1.  # noqa: E501

        :return: The traversal_probability of this VNFLink.
        :rtype: float
        """
        return self._traversal_probability

    @traversal_probability.setter
    def traversal_probability(self, traversal_probability):
        """Sets the traversal_probability of this VNFLink.

        Probability that a request traverses this link. This allows for branchesin the VNFFG (e.g., for load  balancing, etc.). If this parameter is omitted, it is assumed equal to 1.  # noqa: E501

        :param traversal_probability: The traversal_probability of this VNFLink.
        :type traversal_probability: float
        """

        self._traversal_probability = traversal_probability
