# Author: Inaki Pascual
# Copyright (C) 2018 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ns_id: str=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param ns_id: The ns_id of this InlineResponse201.  # noqa: E501
        :type ns_id: str
        """
        self.swagger_types = {
            "ns_id": str
        }

        self.attribute_map = {
            "ns_id": "nsId"
        }

        self._ns_id = ns_id

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse201":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ns_id(self) -> str:
        """Gets the ns_id of this InlineResponse201.


        :return: The ns_id of this InlineResponse201.
        :rtype: str
        """
        return self._ns_id

    @ns_id.setter
    def ns_id(self, ns_id: str):
        """Sets the ns_id of this InlineResponse201.


        :param ns_id: The ns_id of this InlineResponse201.
        :type ns_id: str
        """
        if ns_id is None:
            raise ValueError("Invalid value for `ns_id`, must not be `None`")  # noqa: E501

        self._ns_id = ns_id
