# Author: Inaki Pascual
# Copyright (C) 2018 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, operation_id: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param operation_id: The operation_id of this InlineResponse200.  # noqa: E501
        :type operation_id: str
        """
        self.swagger_types = {
            "operation_id": str
        }

        self.attribute_map = {
            "operation_id": "operationId"
        }

        self._operation_id = operation_id

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse200":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operation_id(self) -> str:
        """Gets the operation_id of this InlineResponse200.


        :return: The operation_id of this InlineResponse200.
        :rtype: str
        """
        return self._operation_id

    @operation_id.setter
    def operation_id(self, operation_id: str):
        """Sets the operation_id of this InlineResponse200.


        :param operation_id: The operation_id of this InlineResponse200.
        :type operation_id: str
        """
        if operation_id is None:
            raise ValueError("Invalid value for `operation_id`, must not be `None`")  # noqa: E501

        self._operation_id = operation_id
