# Copyright (C) 2018 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sap_info import SapInfo  # noqa: F401,E501
from swagger_server import util


class NsInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: str=None, sap_info: List[SapInfo]=None):  # noqa: E501
        """NsInfo - a model defined in Swagger

        :param status: The status of this NsInfo.  # noqa: E501
        :type status: str
        :param sap_info: The sap_info of this NsInfo.  # noqa: E501
        :type sap_info: List[SapInfo]
        """
        self.swagger_types = {
            'status': str,
            'sap_info': List[SapInfo]
        }

        self.attribute_map = {
            'status': 'status',
            'sap_info': 'sapInfo'
        }

        self._status = status
        self._sap_info = sap_info

    @classmethod
    def from_dict(cls, dikt) -> 'NsInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NsInfo of this NsInfo.  # noqa: E501
        :rtype: NsInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this NsInfo.


        :return: The status of this NsInfo.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this NsInfo.


        :param status: The status of this NsInfo.
        :type status: str
        """

        self._status = status

    @property
    def sap_info(self) -> List[SapInfo]:
        """Gets the sap_info of this NsInfo.


        :return: The sap_info of this NsInfo.
        :rtype: List[SapInfo]
        """
        return self._sap_info

    @sap_info.setter
    def sap_info(self, sap_info: List[SapInfo]):
        """Sets the sap_info of this NsInfo.


        :param sap_info: The sap_info of this NsInfo.
        :type sap_info: List[SapInfo]
        """

        self._sap_info = sap_info
