# Author: Jordi Baranda
# Copyright (C) 2019 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NsScaleInfoIm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ns_scaling_aspect_id: str=None, ns_scale_level_id: str=None):  # noqa: E501
        """NsScaleInfoIm - a model defined in Swagger

        :param ns_scaling_aspect_id: The ns_scaling_aspect_id of this NsScaleInfoIm.  # noqa: E501
        :type ns_scaling_aspect_id: str
        :param ns_scale_level_id: The ns_scale_level_id of this NsScaleInfoIm.  # noqa: E501
        :type ns_scale_level_id: str
        """
        self.swagger_types = {
            "ns_scaling_aspect_id": str,
            "ns_scale_level_id": str
        }

        self.attribute_map = {
            "ns_scaling_aspect_id": "nsScalingAspectId",
            "ns_scale_level_id": "nsScaleLevelId"
        }

        self._ns_scaling_aspect_id = ns_scaling_aspect_id
        self._ns_scale_level_id = ns_scale_level_id

    @classmethod
    def from_dict(cls, dikt) -> "NsScaleInfoIm":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NsScaleInfo_im of this NsScaleInfoIm.  # noqa: E501
        :rtype: NsScaleInfoIm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ns_scaling_aspect_id(self) -> str:
        """Gets the ns_scaling_aspect_id of this NsScaleInfoIm.


        :return: The ns_scaling_aspect_id of this NsScaleInfoIm.
        :rtype: str
        """
        return self._ns_scaling_aspect_id

    @ns_scaling_aspect_id.setter
    def ns_scaling_aspect_id(self, ns_scaling_aspect_id: str):
        """Sets the ns_scaling_aspect_id of this NsScaleInfoIm.


        :param ns_scaling_aspect_id: The ns_scaling_aspect_id of this NsScaleInfoIm.
        :type ns_scaling_aspect_id: str
        """
        if ns_scaling_aspect_id is None:
            raise ValueError("Invalid value for `ns_scaling_aspect_id`, must not be `None`")  # noqa: E501

        self._ns_scaling_aspect_id = ns_scaling_aspect_id

    @property
    def ns_scale_level_id(self) -> str:
        """Gets the ns_scale_level_id of this NsScaleInfoIm.


        :return: The ns_scale_level_id of this NsScaleInfoIm.
        :rtype: str
        """
        return self._ns_scale_level_id

    @ns_scale_level_id.setter
    def ns_scale_level_id(self, ns_scale_level_id: str):
        """Sets the ns_scale_level_id of this NsScaleInfoIm.


        :param ns_scale_level_id: The ns_scale_level_id of this NsScaleInfoIm.
        :type ns_scale_level_id: str
        """
        if ns_scale_level_id is None:
            raise ValueError("Invalid value for `ns_scale_level_id`, must not be `None`")  # noqa: E501

        self._ns_scale_level_id = ns_scale_level_id
