# Author: Jordi Baranda
# Copyright (C) 2019 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ScaleNsByStepsDataIm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, scaling_direction: str=None, aspect_id: str=None, number_of_steps: int=None):  # noqa: E501
        """ScaleNsByStepsDataIm - a model defined in Swagger

        :param scaling_direction: The scaling_direction of this ScaleNsByStepsDataIm.  # noqa: E501
        :type scaling_direction: str
        :param aspect_id: The aspect_id of this ScaleNsByStepsDataIm.  # noqa: E501
        :type aspect_id: str
        :param number_of_steps: The number_of_steps of this ScaleNsByStepsDataIm.  # noqa: E501
        :type number_of_steps: int
        """
        self.swagger_types = {
            "scaling_direction": str,
            "aspect_id": str,
            "number_of_steps": int
        }

        self.attribute_map = {
            "scaling_direction": "scalingDirection",
            "aspect_id": "aspectId",
            "number_of_steps": "numberOfSteps"
        }

        self._scaling_direction = scaling_direction
        self._aspect_id = aspect_id
        self._number_of_steps = number_of_steps

    @classmethod
    def from_dict(cls, dikt) -> "ScaleNsByStepsDataIm":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScaleNsByStepsData_im of this ScaleNsByStepsDataIm.  # noqa: E501
        :rtype: ScaleNsByStepsDataIm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scaling_direction(self) -> str:
        """Gets the scaling_direction of this ScaleNsByStepsDataIm.


        :return: The scaling_direction of this ScaleNsByStepsDataIm.
        :rtype: str
        """
        return self._scaling_direction

    @scaling_direction.setter
    def scaling_direction(self, scaling_direction: str):
        """Sets the scaling_direction of this ScaleNsByStepsDataIm.


        :param scaling_direction: The scaling_direction of this ScaleNsByStepsDataIm.
        :type scaling_direction: str
        """
        allowed_values = ["SCALE_IN", "SCALE_OUT"]  # noqa: E501
        if scaling_direction not in allowed_values:
            raise ValueError(
                "Invalid value for `scaling_direction` ({0}), must be one of {1}"
                .format(scaling_direction, allowed_values)
            )

        self._scaling_direction = scaling_direction

    @property
    def aspect_id(self) -> str:
        """Gets the aspect_id of this ScaleNsByStepsDataIm.


        :return: The aspect_id of this ScaleNsByStepsDataIm.
        :rtype: str
        """
        return self._aspect_id

    @aspect_id.setter
    def aspect_id(self, aspect_id: str):
        """Sets the aspect_id of this ScaleNsByStepsDataIm.


        :param aspect_id: The aspect_id of this ScaleNsByStepsDataIm.
        :type aspect_id: str
        """
        if aspect_id is None:
            raise ValueError("Invalid value for `aspect_id`, must not be `None`")  # noqa: E501

        self._aspect_id = aspect_id

    @property
    def number_of_steps(self) -> int:
        """Gets the number_of_steps of this ScaleNsByStepsDataIm.


        :return: The number_of_steps of this ScaleNsByStepsDataIm.
        :rtype: int
        """
        return self._number_of_steps

    @number_of_steps.setter
    def number_of_steps(self, number_of_steps: int):
        """Sets the number_of_steps of this ScaleNsByStepsDataIm.


        :param number_of_steps: The number_of_steps of this ScaleNsByStepsDataIm.
        :type number_of_steps: int
        """

        self._number_of_steps = number_of_steps
