# Author: Jordi Baranda
# Copyright (C) 2019 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location_info_im import LocationInfoIm  # noqa: F401,E501
from swagger_server import util


class VnfLocationConstraintIm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vnf_profile_id: str=None, location_constraints: LocationInfoIm=None):  # noqa: E501
        """VnfLocationConstraintIm - a model defined in Swagger

        :param vnf_profile_id: The vnf_profile_id of this VnfLocationConstraintIm.  # noqa: E501
        :type vnf_profile_id: str
        :param location_constraints: The location_constraints of this VnfLocationConstraintIm.  # noqa: E501
        :type location_constraints: LocationInfoIm
        """
        self.swagger_types = {
            "vnf_profile_id": str,
            "location_constraints": LocationInfoIm
        }

        self.attribute_map = {
            "vnf_profile_id": "vnfProfileId",
            "location_constraints": "locationConstraints"
        }

        self._vnf_profile_id = vnf_profile_id
        self._location_constraints = location_constraints

    @classmethod
    def from_dict(cls, dikt) -> "VnfLocationConstraintIm":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VnfLocationConstraint_im of this VnfLocationConstraintIm.  # noqa: E501
        :rtype: VnfLocationConstraintIm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vnf_profile_id(self) -> str:
        """Gets the vnf_profile_id of this VnfLocationConstraintIm.


        :return: The vnf_profile_id of this VnfLocationConstraintIm.
        :rtype: str
        """
        return self._vnf_profile_id

    @vnf_profile_id.setter
    def vnf_profile_id(self, vnf_profile_id: str):
        """Sets the vnf_profile_id of this VnfLocationConstraintIm.


        :param vnf_profile_id: The vnf_profile_id of this VnfLocationConstraintIm.
        :type vnf_profile_id: str
        """
        if vnf_profile_id is None:
            raise ValueError("Invalid value for `vnf_profile_id`, must not be `None`")  # noqa: E501

        self._vnf_profile_id = vnf_profile_id

    @property
    def location_constraints(self) -> str:
        """Gets the location_constraints of this VnfLocationConstraintIm.


        :return: The location_constraints of this VnfLocationConstraintIm.
        :rtype: str
        """
        return self._location_constraints

    @location_constraints.setter
    def location_constraints(self, location_constraints: str):
        """Sets the location_constraints of this VnfLocationConstraintIm.


        :param location_constraints: The location_constraints of this VnfLocationConstraintIm.
        :type location_constraints: str
        """
        if location_constraints is None:
            raise ValueError("Invalid value for `location_constraints`, must not be `None`")  # noqa: E501

        self._location_constraints = location_constraints
