# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PAResponseUsedNFVIPops(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, nfvi_po_pid=None, mapped_vn_fs=None):  # noqa: E501
        """PAResponseUsedNFVIPops - a model defined in Swagger

        :param nfvi_po_pid: The nfvi_po_pid of this PAResponseUsedNFVIPops.  # noqa: E501
        :type nfvi_po_pid: str
        :param mapped_vn_fs: The mapped_vn_fs of this PAResponseUsedNFVIPops.  # noqa: E501
        :type mapped_vn_fs: List[str]
        """
        self.swagger_types = {
            'nfvi_po_pid': str,
            'mapped_vn_fs': List[str]
        }

        self.attribute_map = {
            'nfvi_po_pid': 'NFVIPoPID',
            'mapped_vn_fs': 'mappedVNFs'
        }

        self._nfvi_po_pid = nfvi_po_pid
        self._mapped_vn_fs = mapped_vn_fs

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PAResponse_usedNFVIPops of this PAResponseUsedNFVIPops.  # noqa: E501
        :rtype: PAResponseUsedNFVIPops
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nfvi_po_pid(self):
        """Gets the nfvi_po_pid of this PAResponseUsedNFVIPops.

        NFVI PoP ID  # noqa: E501

        :return: The nfvi_po_pid of this PAResponseUsedNFVIPops.
        :rtype: str
        """
        return self._nfvi_po_pid

    @nfvi_po_pid.setter
    def nfvi_po_pid(self, nfvi_po_pid):
        """Sets the nfvi_po_pid of this PAResponseUsedNFVIPops.

        NFVI PoP ID  # noqa: E501

        :param nfvi_po_pid: The nfvi_po_pid of this PAResponseUsedNFVIPops.
        :type nfvi_po_pid: str
        """

        self._nfvi_po_pid = nfvi_po_pid

    @property
    def mapped_vn_fs(self):
        """Gets the mapped_vn_fs of this PAResponseUsedNFVIPops.

        all VNFs mapped in this NFVI PoP  # noqa: E501

        :return: The mapped_vn_fs of this PAResponseUsedNFVIPops.
        :rtype: List[str]
        """
        return self._mapped_vn_fs

    @mapped_vn_fs.setter
    def mapped_vn_fs(self, mapped_vn_fs):
        """Sets the mapped_vn_fs of this PAResponseUsedNFVIPops.

        all VNFs mapped in this NFVI PoP  # noqa: E501

        :param mapped_vn_fs: The mapped_vn_fs of this PAResponseUsedNFVIPops.
        :type mapped_vn_fs: List[str]
        """

        self._mapped_vn_fs = mapped_vn_fs
