# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LLDestination(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id=None, gw_ip_address=None):  # noqa: E501
        """LLDestination - a model defined in Swagger

        :param id: The id of this LLDestination.  # noqa: E501
        :type id: str
        :param gw_ip_address: The gw_ip_address of this LLDestination.  # noqa: E501
        :type gw_ip_address: str
        """
        self.swagger_types = {
            'id': str,
            'gw_ip_address': str
        }

        self.attribute_map = {
            'id': 'id',
            'gw_ip_address': 'GwIpAddress'
        }

        self._id = id
        self._gw_ip_address = gw_ip_address

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LL_destination of this LLDestination.  # noqa: E501
        :rtype: LLDestination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this LLDestination.

        Destination NFVIPoP id  # noqa: E501

        :return: The id of this LLDestination.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LLDestination.

        Destination NFVIPoP id  # noqa: E501

        :param id: The id of this LLDestination.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def gw_ip_address(self):
        """Gets the gw_ip_address of this LLDestination.

        Endpoint IP address  # noqa: E501

        :return: The gw_ip_address of this LLDestination.
        :rtype: str
        """
        return self._gw_ip_address

    @gw_ip_address.setter
    def gw_ip_address(self, gw_ip_address):
        """Sets the gw_ip_address of this LLDestination.

        Endpoint IP address  # noqa: E501

        :param gw_ip_address: The gw_ip_address of this LLDestination.
        :type gw_ip_address: str
        """
        if gw_ip_address is None:
            raise ValueError("Invalid value for `gw_ip_address`, must not be `None`")  # noqa: E501

        self._gw_ip_address = gw_ip_address
