# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PAResponseUsedVLs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, nfvi_po_p=None, mapped_v_ls=None):  # noqa: E501
        """PAResponseUsedVLs - a model defined in Swagger

        :param nfvi_po_p: The nfvi_po_p of this PAResponseUsedVLs.  # noqa: E501
        :type nfvi_po_p: str
        :param mapped_v_ls: The mapped_v_ls of this PAResponseUsedVLs.  # noqa: E501
        :type mapped_v_ls: List[str]
        """
        self.swagger_types = {
            'nfvi_po_p': str,
            'mapped_v_ls': List[str]
        }

        self.attribute_map = {
            'nfvi_po_p': 'NFVIPoP',
            'mapped_v_ls': 'mappedVLs'
        }

        self._nfvi_po_p = nfvi_po_p
        self._mapped_v_ls = mapped_v_ls

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PAResponse_usedVLs of this PAResponseUsedVLs.  # noqa: E501
        :rtype: PAResponseUsedVLs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nfvi_po_p(self):
        """Gets the nfvi_po_p of this PAResponseUsedVLs.

        NFVIPoP ID  # noqa: E501

        :return: The nfvi_po_p of this PAResponseUsedVLs.
        :rtype: str
        """
        return self._nfvi_po_p

    @nfvi_po_p.setter
    def nfvi_po_p(self, nfvi_po_p):
        """Sets the nfvi_po_p of this PAResponseUsedVLs.

        NFVIPoP ID  # noqa: E501

        :param nfvi_po_p: The nfvi_po_p of this PAResponseUsedVLs.
        :type nfvi_po_p: str
        """

        self._nfvi_po_p = nfvi_po_p

    @property
    def mapped_v_ls(self):
        """Gets the mapped_v_ls of this PAResponseUsedVLs.

        all VLs mapped in this LL between NFVI PoP  # noqa: E501

        :return: The mapped_v_ls of this PAResponseUsedVLs.
        :rtype: List[str]
        """
        return self._mapped_v_ls

    @mapped_v_ls.setter
    def mapped_v_ls(self, mapped_v_ls):
        """Sets the mapped_v_ls of this PAResponseUsedVLs.

        all VLs mapped in this LL between NFVI PoP  # noqa: E501

        :param mapped_v_ls: The mapped_v_ls of this PAResponseUsedVLs.
        :type mapped_v_ls: List[str]
        """

        self._mapped_v_ls = mapped_v_ls
