# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VLCost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cost=None, nfvi_po_p=None):  # noqa: E501
        """VLCost - a model defined in Swagger

        :param cost: The cost of this VLCost.  # noqa: E501
        :type cost: float
        :param nfvi_po_p: The nfvi_po_p of this VLCost.  # noqa: E501
        :type nfvi_po_p: str
        """
        self.swagger_types = {
            'cost': float,
            'nfvi_po_p': str
        }

        self.attribute_map = {
            'cost': 'cost',
            'nfvi_po_p': 'NFVIPoP'
        }

        self._cost = cost
        self._nfvi_po_p = nfvi_po_p

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VLCost of this VLCost.  # noqa: E501
        :rtype: VLCost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cost(self):
        """Gets the cost of this VLCost.

        Cost of Mbps to use a VL inside the specified NFVIPoP  # noqa: E501

        :return: The cost of this VLCost.
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this VLCost.

        Cost of Mbps to use a VL inside the specified NFVIPoP  # noqa: E501

        :param cost: The cost of this VLCost.
        :type cost: float
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")  # noqa: E501

        self._cost = cost

    @property
    def nfvi_po_p(self):
        """Gets the nfvi_po_p of this VLCost.

        NFVIPoPs identifier  # noqa: E501

        :return: The nfvi_po_p of this VLCost.
        :rtype: str
        """
        return self._nfvi_po_p

    @nfvi_po_p.setter
    def nfvi_po_p(self, nfvi_po_p):
        """Sets the nfvi_po_p of this VLCost.

        NFVIPoPs identifier  # noqa: E501

        :param nfvi_po_p: The nfvi_po_p of this VLCost.
        :type nfvi_po_p: str
        """
        if nfvi_po_p is None:
            raise ValueError("Invalid value for `nfvi_po_p`, must not be `None`")  # noqa: E501

        self._nfvi_po_p = nfvi_po_p
