# Author: Jordi Baranda
# Copyright (C) 2019 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FederatedInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, nsd_id: str=None):  # noqa: E501
        """FederatedInfo - a model defined in Swagger

        :param nsd_id: The nsd_id of this FederatedInfo.  # noqa: E501
        :type nsd_id: str
        """
        self.swagger_types = {
            'nsd_id': str
        }

        self.attribute_map = {
            'nsd_id': 'nsdId'
        }

        self._nsd_id = nsd_id

    @classmethod
    def from_dict(cls, dikt) -> 'FederatedInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FederatedInfo of this FederatedInfo.  # noqa: E501
        :rtype: FederatedInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nsd_id(self) -> str:
        """Gets the nsd_id of this FederatedInfo.


        :return: The nsd_id of this FederatedInfo.
        :rtype: str
        """
        return self._nsd_id

    @nsd_id.setter
    def nsd_id(self, nsd_id: str):
        """Sets the nsd_id of this FederatedInfo.


        :param nsd_id: The nsd_id of this FederatedInfo.
        :type nsd_id: str
        """
        if nsd_id is None:
            raise ValueError("Invalid value for `nsd_id`, must not be `None`")  # noqa: E501

        self._nsd_id = nsd_id
