# Author: Jordi Baranda
# Copyright (C) 2019 CTTC/CERCA
# License: To be defined. Currently use is restricted to partners of the 5G-Transformer project,
#          http://5g-transformer.eu/, no use or redistribution of any kind outside the 5G-Transformer project is
#          allowed.
# Disclaimer: this software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.key_value_pair import KeyValuePair  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network_info: KeyValuePair=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param network_info: The network_info of this InlineResponse2001.  # noqa: E501
        :type network_info: KeyValuePair
        """
        self.swagger_types = {
            'network_info': KeyValuePair
        }

        self.attribute_map = {
            'network_info': 'networkInfo'
        }

        self._network_info = network_info

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_info(self) -> KeyValuePair:
        """Gets the network_info of this InlineResponse2001.


        :return: The network_info of this InlineResponse2001.
        :rtype: KeyValuePair
        """
        return self._network_info

    @network_info.setter
    def network_info(self, network_info: KeyValuePair):
        """Sets the network_info of this InlineResponse2001.


        :param network_info: The network_info of this InlineResponse2001.
        :type network_info: KeyValuePair
        """
        if network_info is None:
            raise ValueError("Invalid value for `network_info`, must not be `None`")  # noqa: E501

        self._network_info = network_info
